### ISSUE TITLE
New config file paradigm

### ISSUE THREAD

**Issue by nsoblath** [project8/psyllid#21]
Psyllid needs a new config-file paradigm to support production use of the software.  The current version has sufficed well for development, but is too simplistic for what we'll need to do.  

Comments are welcome.

## To-do list
- [x] stream manager (new class)
  * Hold information about streams separately, so they can be independently accessed/removed/added
  * Node names provided by user/preset are only unique within each stream
  * No access/adding/removing individual nodes
  * Other than where noted, copies functionality from node_manager
  - [x] Add stream from `preset` param_node
    - [x] If `preset` is a string value, request that preset from the preset factory
    - [x] If `preset` is a node, create the preset (see node_config_preset below), then request it from the preset factory
  - [x] Node names must be prepended by `[stream #]_` when midge is reset with the new nodes
    - [x] Amended name given to the node_builder
    - [x] Name instances within connection strings must be amended (probably use [boost::replace_all](ww.boost.org/doc/libs/1_63_0/doc/html/boost/algorithm/replace_all.html))
  - [x] Stream-wide configuration information is added to each node's config
  - [x] Control from run_server
- [x] node_config_preset (update)
  - [x] Static function to create a preset from a param_node and register it
- [x] Device configurations need to be accessible from within daq nodes
  - [x] Stream-wide configuration information (e.g. `device`) is added to each node's config by the stream_manager
  - [x] Particular node_builders will know when to look for that stream-wide information (streaming_writer and egg_writer, to start with)
- [x] Remove node_manager

## Example configuration file 
For a 3-channel FPA DAQ:
```yaml
amqp:
    broker: localhost
    broker-port: 5672
    request-exchange: requests
    alert-exchange: alerts
    queue: psyllid
    listen-timeout-ms: 100

daq:
    activate-at-startup: true

streams:
    - preset: str-1ch-fpa

      device:
          n-channels: 1
          bit-depth: 8
          data-type-size: 1
          sample-size: 2
          record-size: 4096
          acq-rate: 100 # MHz
          v-offset: 0.0
          v-range: 0.5

      prs:
          length: 10
          port: 23530
          interface: eth1
          n-blocks: 64
          block-size: 4194304
          frame-size: 2048

    - preset: str-1ch-fpa

      device:
          n-channels: 1
          bit-depth: 8
          data-type-size: 1
          sample-size: 2
          record-size: 4096
          acq-rate: 100 # MHz
          v-offset: 0.0
          v-range: 0.5

      prs:
          length: 10
          port: 23530
          interface: eth2
          n-blocks: 64
          block-size: 4194304
          frame-size: 2048
   
    - preset:  # this preset is identical to str-1ch-fpa; it's given like this as a demonstration of how to specify a preset in a configuration file
          name: str-1ch-fpa-alt
          nodes:
            - { type: packet-receiver-fpa,   name: prs }
            - { type: tf-roach-receiver,     name: tfrr }
            - { type: streaming-writer,      name: strw }
            - { type: term-freq-data,        name: term }
          connections:
            - "prf.out_0:tfrr.in_0"
            - "tfrr.out_0:strw.in_0"
            - "tfrr.out_1:term.in_0"

      device:
          n-channels: 1
          bit-depth: 8
          data-type-size: 1
          sample-size: 2
          record-size: 4096
          acq-rate: 100 # MHz
          v-offset: 0.0
          v-range: 0.5

      prs:
          length: 10
          port: 23530
          interface: eth3
          n-blocks: 64
          block-size: 4194304
          frame-size: 2048
```

**Comment by nsoblath** [comment]
Completed in commit 426e4736de005e0efee277d6f25968dd66f60222
